/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: NORBERTO-3D (https://sketchfab.com/norberto3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042
Title: phoenix bird
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Object_7: THREE.SkinnedMesh
        Object_8: THREE.SkinnedMesh
        _rootJoint: THREE.Bone
    }
    materials: {
        MatI_Ride_FengHuang_01a: THREE.MeshStandardMaterial
        MatI_Ride_FengHuang_01b: THREE.MeshStandardMaterial
    }
}

type ActionName = 'Take 001'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function FlyingBird(props: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group>(null)
    const { nodes, materials, animations } = useGLTF('/Flying-Bird/scene.gltf') as GLTFResult
    const { actions } = useAnimations<GLTFActions>(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group
                    name="Sketchfab_model"
                    position={[-0.62473196, 0, -17.13710403]}
                    rotation={[-Math.PI / 2, 0, 0.05291625]}
                    scale={[0.99999998, 0.99999998, 1]}
                    userData={{ name: 'Sketchfab_model' }}>
                    <group
                        name="5f59736c86d4457fa045aec4aea6b7e0fbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        userData={{ name: '5f59736c86d4457fa045aec4aea6b7e0.fbx' }}>
                        <group name="Object_2" userData={{ name: 'Object_2' }}>
                            <group name="RootNode" userData={{ name: 'RootNode' }}>
                                <group name="Object_4" userData={{ name: 'Object_4' }}>
                                    <primitive object={nodes._rootJoint} />
                                    <skinnedMesh
                                        name="Object_7"
                                        geometry={nodes.Object_7.geometry}
                                        material={materials.MatI_Ride_FengHuang_01a}
                                        skeleton={nodes.Object_7.skeleton}
                                        userData={{ name: 'Object_7' }}
                                    />
                                    <skinnedMesh
                                        name="Object_8"
                                        geometry={nodes.Object_8.geometry}
                                        material={materials.MatI_Ride_FengHuang_01b}
                                        skeleton={nodes.Object_8.skeleton}
                                        userData={{ name: 'Object_8' }}
                                    />
                                    <group
                                        name="Object_6"
                                        rotation={[-Math.PI / 2, 0, 0]}
                                        userData={{ name: 'Object_6' }}
                                    />
                                    <group
                                        name="AMesh_Ride_FengHuang_01"
                                        rotation={[-Math.PI / 2, 0, 0]}
                                        userData={{ name: 'AMesh_Ride_FengHuang_01' }}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/Flying-Bird/scene.gltf')

