/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: david.campuzano (https://sketchfab.com/david.campuzano)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hacker-room-stylized-a0cfe6edf2dd494c8a95addf6bb13a10
Title: Hacker Room - Stylized
*/

import React, { useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'

const context = createContext()

export function Instances({ children, ...props }) {
    const { nodes } = useGLTF('/Hacker-Room-Stylized/scene.gltf')
    const instances = useMemo(
        () => ({
            Computercomputermat: nodes.computer_computer_mat_0,
            Serverservermat: nodes.server_server_mat_0,
            VhsvhsPlayermat: nodes.vhs_vhsPlayer_mat_0,
            Shelfstandmat: nodes.shelf_stand_mat_0,
            Keyboardmatmatmat: nodes.keyboard_mat_mat_mat_0,
            Armarmmat: nodes.arm_arm_mat_0,
            Tvtvmat: nodes.Tv_tv_mat_0,
            Tabletablemat: nodes.table_table_mat_0,
            Cablescablesmat: nodes.Cables_cables_mat_0,
            Propspropsmat: nodes.props_props_mat_0,
            Screenscreens: nodes.screen_screens_0,
            Screenglassglass: nodes.screen_glass_glass_0,
            Groundgroundmat: nodes.Ground_ground_mat_0,
            Peripheralskeymat: nodes.peripherals_key_mat_0,
        }),
        [nodes]
    )
    return (
        <Merged meshes={instances} {...props}>
            {(instances) => <context.Provider value={instances}>{children}</context.Provider>}
        </Merged>
    )
}

export function Model(props) {
    const instances = useContext(context)

    if (!instances) {
        console.warn('Model must be wrapped with <Instances> component')
        return null
    }

    return (
        <group {...props} dispose={null}>
            <group>
                <group rotation={[-Math.PI / 2, 0, 0]}>
                    <group rotation={[Math.PI / 2, 0, 0]}>
                        <group>
                            <instances.Computercomputermat />
                            <instances.Serverservermat />
                            <instances.VhsvhsPlayermat />
                            <instances.Shelfstandmat />
                            <instances.Keyboardmatmatmat />
                            <instances.Armarmmat />
                            <instances.Tvtvmat />
                            <instances.Tabletablemat />
                            <instances.Cablescablesmat />
                            <instances.Propspropsmat />
                            <instances.Screenscreens />
                            <instances.Screenglassglass />
                            <instances.Groundgroundmat />
                            <instances.Peripheralskeymat />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/Hacker-Room-Stylized/scene.gltf')


